espr/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include, url
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('e_commerce/', include(('ecommerce.urls'), namespace='e_commerce')),
    url(r'^paypal/', include('paypal.standard.ipn.urls')),
    path('main/', include('main_app.urls')),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main_app/urls.py
from django.urls import path, re_path
from . import views
from django.contrib.auth import views as auth_views

app_name = "main_app"

urlpatterns = [
    path('test', views.test, name='test'),
    path('home', views.home, name='home'),

    path('signup', views.signup, name='signup'),
    path('confirm_email/<int:id_user>/<str:token_email>', views.confirm_email_signup, name='confirm_email_signup'),#traitement pour confirmer un email via le lien envoyé par mail
    path('login', views.log_in, name='log_in'),
    path('logout', views.log_out, name='log_out'),
    path('confirm_mail/resend', views.confirm_mail_resend, name='confirm_mail_resend'),# renvoyer un autre mail de confirmation
    path('contactus', views.contactus, name='contactus'),

    # Views pour reset password
    path('reset-password', views.password_reset, name='password_reset'),
    path('reset-password/done', auth_views.password_reset_done,
         {'template_name': 'authentification/reset_password_done.html'},name='password_reset_done'),
    re_path('reset-password/confirm/(?P<uidb64>[0-9A-Za-z]+)-(?P<token>.+)/$', auth_views.password_reset_confirm,
            {'template_name': 'authentification/reset_password_confirm.html',
                'post_reset_redirect': 'main_app:password_reset_complete'}, name='password_reset_confirm'),
    path('reset-password/complete', auth_views.password_reset_complete,
         {'template_name': 'authentification/reset_password_complete.html'}, name='password_reset_complete'),

]

main_app/models.py
from django.db import models
from django.contrib.auth.models import User


class Image(models.Model):
    image = models.ImageField(default="")

    def __str__(self):
        return str(self.image)


class TypeEntreprise(models.Model):
    types = (('publique', 'publique'), ('prive', 'prive'))
    type = models.CharField(max_length=255, choices=types)


class Entreprise(models.Model):
    secteurs = (('Publique', 'Publique'), ('Prive', 'Privé'))
    nom = models.CharField(max_length=300, null=False, blank=False)
    activite = models.CharField(max_length=255, null=False, blank=False)
    secteurActivite = models.CharField(choices=secteurs, null=False, blank=False, max_length=255)
    capitale = models.DecimalField(null=False, blank=False, decimal_places=2, max_digits=10)
    pays = models.CharField(max_length=255, blank=False, null=False)
    ville = models.CharField(max_length=255, null=False, blank=False)
    codePostal = models.IntegerField()
    telephone = models.DecimalField(max_digits=10, decimal_places=2)
    siteInternet = models.CharField(max_length=300)
    typeEntreprise = models.ForeignKey(TypeEntreprise, on_delete=models.CASCADE)


type_customer = (('Ordinary', 'Ordinary'), ('Professional', 'Professional'), ('Supplier', 'Supplier'), ('Seller', 'Seller'))


class Profil(models.Model):
    user = models.OneToOneField(User, blank=True, null=True, on_delete=models.CASCADE)
    token_email = models.CharField(max_length=300, blank=True, null=True, default="")
    token_email_expiration = models.DateTimeField(blank=True, null=True)
    tel = models.CharField(max_length=300, blank=True, null=True, default="")
    is_professional = models.BooleanField(default=False)
    is_supplier = models.BooleanField(default=False)
    is_seller = models.BooleanField(default=False)

    def __str__(self):
        return self.user.username


class Contact(models.Model):
    full_name = models.CharField( max_length=300)
    email = models.EmailField()
    message = models.TextField()
    
    def __str__(self):
        return self.full_name

main_app/forms.py
from django import forms
from .models import *
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm


class FormProfilInscription(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())
    confirmer_votre_mot_de_passe = forms.CharField(widget=forms.PasswordInput())
    email = forms.EmailField()

    class Meta:
        model = User
        fields = ('username','email','first_name','last_name','password')

    def clean(self):
        cleaned_data = super(FormProfilInscription, self).clean()
        password = cleaned_data.get("password")
        confirm_password = cleaned_data.get("confirmer_votre_mot_de_passe")

        email = cleaned_data.get('email')
        username = cleaned_data.get('username')

        if email and User.objects.filter(email=email).exclude(username=username).exists():
            self.add_error('email', "Cet E-mail est déjà enregistré.")

        if password != confirm_password:
            self.add_error("password", "Les deux mot de passes ne sont pas identiques.")


class loginform(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())

    class Meta:
        model = User
        fields = ['email', 'password']


class userform(UserCreationForm):
    class Meta:
        model = User
        fields = ['username', 'password1', 'password2', 'email', 'first_name', 'last_name']


class userProfile(forms.ModelForm):
    class Meta:
        model = Profil
        exclude = ['last_logout', 'user']


class PhotoForm(forms.ModelForm):
    class Meta:
        model = Image
        fields = '__all__'


class formConfirmEmail(forms.ModelForm):
    class Meta:
        model = User
        fields = ['email']


class ContactForm(forms.ModelForm):
    class Meta:
        model = Contact
        fields = '__all__'

main_app/views.py
from django.shortcuts import render, redirect,resolve_url
from django.http import HttpResponse,Http404,HttpResponseRedirect
from .models import *
from .forms import *
from django.core.mail import send_mail
from django.template.loader import  get_template
from django.utils.crypto import get_random_string
from datetime import datetime, timedelta
from django.utils import timezone
from django.shortcuts import get_object_or_404
from django.contrib.auth.forms import  PasswordResetForm
from django.contrib.auth import logout , login , authenticate
from django.contrib import messages
from django.urls import reverse
from django.utils.timezone import now
from django.contrib.auth.tokens import default_token_generator
from django.template.response import TemplateResponse

# Create your views here.


def test(request):
    return render(request,'base_main.html')


def signup(request):
    if request.method == 'POST':
        form_inscription = FormProfilInscription(request.POST)
        if form_inscription.is_valid():
            user = form_inscription.save(commit=False)
            user.is_active = False
            user.email = user.email.lower()
            user.save()
            profil = Profil.objects.get_or_create(user=user)[0]
            profil.save()

            send_confirmation_signup_mail(request, user)# une méthode qu'on a nous meme défini ( un peu plus bas )

            return render(request, 'authentification/sign_up.html', {'form_inscription': form_inscription,})
    else:
        form_inscription = FormProfilInscription()

    return render(request,'authentification/sign_up.html',{'form_inscription':form_inscription})


def confirm_email_signup(request,id_user,token_email):
    user = get_object_or_404(User, id=id_user)

    if user.is_active:
        messages.warning(request, "Votre email est déjà confirmé.")
        return redirect('main_app:log_in')

    if user.profil.token_email_expiration <= timezone.now():
        messages.warning(request,
                         "Votre lien a expiré. <strong><a href='/main/confirm_mail/resend'>Renvoyer l'email</a></strong> ")
        return redirect('main_app:log_in')
    else:
        if user.profil.token_email == token_email:
            user.is_active = True
            user.save()
            messages.success(request,"Votre email a été confirmé.")
            return redirect('main_app:log_in')
        else:
            raise Http404("Une erreur s'est produite.")

    return redirect('main_app:log_in')


def log_in(request):
    if request.user.is_authenticated:
        return HttpResponse('authentifié')
    if request.method == 'POST':
        email = request.POST.get('email').lower()
        password = request.POST.get('password')

        try:
            user = User.objects.get(email=email.lower())  # on le récupère juste pour vérifier s'il est actif
        except:
            user = None

        if user is not None:
            if not user.is_active:
                messages.warning(request,
                                 "Votre compte n'est pas encore activé, Veuiller l'activer en cliquant sur le lien vous a été envoyé via mail. <strong><a href='/main/confirm_mail/resend'>Renvoyer l'email</a></strong> ")
                return redirect('main_app:log_in')
            else: # S'il a un email valide + est actif , on verifie son mdp
                user = authenticate(username=email,
                                        password=password)  # ici on le récupère pour voir s'il a tapé le bon mdp
                if user is not None: # Si l'email valide + password  valide + actif
                    login(request, user)
                    return redirect('main_app:home')
                else:
                    messages.error(request, "L'email ou le mot de passe est incorrect.")
                    return redirect('main_app:log_in')


    form_login = loginform()
    return render(request, "authentification/login.html", {'form_login':form_login})


def password_reset(request, is_admin_site=False,template_name='authentification/reset_password_form.html',email_template_name='emails/reset_password_email.html',subject_template_name='authentification/reset_password_subject.txt',password_reset_form=PasswordResetForm,token_generator=default_token_generator,post_reset_redirect=None,from_email=None,current_app=None,extra_context=None,html_email_template_name='emails/reset_password_email.html'):
    if post_reset_redirect is None:
        post_reset_redirect = reverse('main_app:password_reset_done')
    else:
        post_reset_redirect = resolve_url(post_reset_redirect)
    if request.method == "POST":
        form = password_reset_form(request.POST)
        if form.is_valid():
            opts = {
                'use_https': request.is_secure(),
                'token_generator': token_generator,
                'from_email': from_email,
                'email_template_name': email_template_name,
                'subject_template_name': subject_template_name,
                'request': request,
                'html_email_template_name': html_email_template_name,
            }
            if is_admin_site:
                opts = dict(opts, domain_override=request.get_host())
            form.save(**opts)
            return HttpResponseRedirect(post_reset_redirect)
    else:
        form = password_reset_form()
    context = {
        'form_reset_password': form,
        'title': ('Password reset'),
    }
    if extra_context is not None:
        context.update(extra_context)

    if current_app is not None:
        request.current_app = current_app

    return TemplateResponse(request, template_name, context)


def log_out(request):
    if request.user.is_authenticated:
        logout(request)
        return redirect('main_app:home')
    else:
        return redirect('main_app:log_in')


def home(request):
    return render(request,'home.html')


def send_confirmation_signup_mail(request, user=None): # Methode normal , pas une vue, utilisée pour envoyer un mail dans la view signup et confirm_mail_resend
    if user is None:
        messages.error(request, 'Une erreur s\'est produite.<br>Peut être que l\'email indiqué n\'est pas enregistré.<br>Veuillez Réessayer ')
    elif user.is_active:
        messages.warning(request,
                         'Votre compte est déjà activé')
    else:
        generated_token = get_random_string(length=32)
        user.profil.token_email = generated_token
        user.profil.token_email_expiration = datetime.now() + timedelta(days=2)
        user.profil.save()
        message = get_template('emails/signup_confirm_email.html').render({'user': user})

        send_mail(
            'Finalisez votre inscription sur www.socialfly.com',
            message,
            'admin@socifly.com',
            [user.email],
            fail_silently=False,
            html_message=message,
        )
        messages.success(request,
                         'Un e-mail de vérification vous a été envoyé à l\'adresse '+user.email+'.<br>Cliquez sur le lien inclu dans l\'e-mail pour activer votre compte. ')


def confirm_mail_resend(request): #Vue utilisée quand on clique sur Renvoyer un autre email et qu'on tape l'email dans le formulaire, on le recupere par get
    if 'email' in request.GET:
        try:
            user = User.objects.get(email=request.GET.get('email').lower())
        except:
            user = None

        send_confirmation_signup_mail(request, user)

    return render(request, 'authentification/confirm_mail_form.html')


def contactus(request):

    if request.method == 'POST':
        contact_form = ContactForm(request.POST)
        if contact_form.is_valid():
            contact_form.save(commit=True)
            messages.success(request,'Votre message a été envoyé.<br>Nous vous répondrons dans les plus bref délais.')
            return render(request, 'main/contactus.html', {'contact_form': contact_form})
    else:
        contact_form = ContactForm()

    return render(request,'main/contactus.html',{'contact_form':contact_form})

main_app/templates/authentification/base_authentification.html
{% extends 'base_main.html' %}
{% load staticfiles %}
{% load widget_tweaks %}


{% block title %}
{{ block.super }}
{% endblock title %}


{% block stylesheets %}
{{ block.super }}

<link rel="icon" type="image/png" href="{% static 'images/icons/favicon.ico' %}"/>
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static 'vendor/bootstrap/css/bootstrap.min.css' %}">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static 'fonts/font-awesome-4.7.0/css/font-awesome.min.css' %}">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static 'vendor/animate/animate.css' %}">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static 'vendor/css-hamburgers/hamburgers.min.css' %}">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static 'vendor/select2/select2.min.css' %}">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static 'css/util.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'css/main.css' %}">

{% endblock stylesheets %}



{% block content %}
{{ block.super }}

<div class="limiter">
		<div class="container-login100">
			<div class="wrap-login100">

				{% block leftimage %}
					<div class="login100-pic js-tilt" data-tilt>
						<img src="{% static 'images/img-01.png' %}" alt="IMG">
					</div>
				{% endblock leftimage %}


				{% block form %}

                {% endblock form %}

			</div>
		</div>
	</div>


{% endblock content %}



{% block footer %}
{{ block.super }}
{% endblock footer %}



{% block scripts %}
{{ block.super }}

<!--===============================================================================================-->
	<script src="{% static 'vendor/jquery/jquery-3.2.1.min.js' %}"></script>
<!--===============================================================================================-->
	<script src="{% static 'vendor/bootstrap/js/popper.js' %}"></script>
	<script src="{% static 'vendor/bootstrap/js/bootstrap.min.js' %}"></script>
<!--===============================================================================================-->
	<script src="{% static 'vendor/select2/select2.min.js' %}"></script>
<!--===============================================================================================-->
	<script src="{% static 'vendor/tilt/tilt.jquery.min.js' %}"></script>
	<script >
		$('.js-tilt').tilt({
			scale: 1.1
		})
	</script>
<!--===============================================================================================-->
	<script src="{% static 'js/main.js' %}"></script>

{% endblock scripts %}

main_app/templates/authentification/confirm_mail_form.html
{% extends 'authentification/base_authentification.html' %}
{% load staticfiles %}
{% load widget_tweaks %}

{% block title} {{block.super}} - Récupérer mon mot de passe{% endblock title}

{% block form %}

<form class="login100-form validate-form" method="GET" >
    {% csrf_token %}

    <span class="login100-form-title"> Envoyer un mail de confirmation 	</span>

    {% include "messages.html" %}

    {% for error in form_confirm_mail.email.errors %}
        <span class="error-block">{{ error }}</span>
    {% endfor %}
    <div class="wrap-input100 validate-input" >
        <input type="email" class="input100" placeholder="Email" name="email">
        <span class="focus-input100"></span>
        <span class="symbol-input100">
            <i class="fa fa-envelope" aria-hidden="true"></i>
        </span>
    </div>


    <div class="container-login100-form-btn">
        <button class="login100-form-btn">
            Continuer
        </button>
    </div>

    <div class="text-center p-t-12">


        <a class="txt2" href="/main/login">
            Se connecter
        </a>
        |
        <a class="txt2" href="/main/signup">
            S'inscrire
        </a>
    </div>
</form>

{% endblock form %}

main_app/templates/authentification/login.html
{% extends 'authentification/base_authentification.html' %}
{% load staticfiles %}
{% load widget_tweaks %}

{% block title %} {{block.super}} S'inscrire{% endblock title %}

{% block form %}

<form class="login100-form validate-form" method="POST" action="/main/login">
    {% csrf_token %}

    <span class="login100-form-title"> Connexion 	</span>

    {% include "messages.html" %}


    {% for error in form_login.email.errors %}
        <span class="error-block">{{ error }}</span>
    {% endfor %}
    <div class="wrap-input100 validate-input" >
        {% render_field form_login.email class="input100" placeholder="Email" %}
        <span class="focus-input100"></span>
        <span class="symbol-input100">
            <i class="fa fa-envelope" aria-hidden="true"></i>
        </span>
    </div>

    {% for error in form_login.password.errors %}
        <span class="error-block">{{ error }}</span>
    {% endfor %}
    <div class="wrap-input100 validate-input" >
        {% render_field form_login.password class="input100" placeholder="Mot de passe" %}
        <span class="focus-input100"></span>
        <span class="symbol-input100">
            <i class="fa fa-key" aria-hidden="true"></i>
        </span>
    </div>






    <div class="container-login100-form-btn">
        <button class="login100-form-btn">
            Se connecter
        </button>
    </div>

    <div class="text-center p-t-12">


        <a class="txt2" href="/main/reset-password">
            Mot de passe oublié?
        </a>
        |
        <a class="txt2" href="/main/signup">
            S'inscrire
        </a>
    </div>
</form>

{% endblock form %}

main_app/templates/authentification/reset_password_complete.html
{% extends 'authentification/base_authentification.html' %}
{% load staticfiles %}
{% load widget_tweaks %}

{% block title} {{block.super}} - Récupérer mon mot de passe{% endblock title}

{% block form %}

<form class="login100-form validate-form" >


    <span class="login100-form-title"> 	</span>
    <div class="alert alert-success ">
       Mot de passe changé avec succès. <a href="/main/login">Cliquez ici</a> pour vous authentifier
    </div>


</form>

{% endblock form %}

main_app/templates/authentification/reset_password_confirm.html
{% extends 'authentification/base_authentification.html' %}
{% load staticfiles %}
{% load widget_tweaks %}

{% block title} {{block.super}} - Redéfinir le mot de passe{% endblock title}

{% block form %}

<form class="login100-form validate-form" method="POST" >
    {% if form %}
    {% csrf_token %}

    <span class="login100-form-title"> Saisissez votre noveau mot de passe 	</span>

    {% include "messages.html" %}


    {% for error in form.new_password1.errors %}
        <span class="error-block">{{ error }}</span>
    {% endfor %}
    <div class="wrap-input100 validate-input" >
        {% render_field form.new_password1 class="input100" placeholder="Nouveau mot de passe" %}
        <span class="focus-input100"></span>
        <span class="symbol-input100">
            <i class="fa fa-envelope" aria-hidden="true"></i>
        </span>
    </div>

    {% for error in form.new_password2.errors %}
        <span class="error-block">{{ error }}</span>
    {% endfor %}
    <div class="wrap-input100 validate-input" >
        {% render_field form.new_password2 class="input100" placeholder="Confirmer le mot de passe" %}
        <span class="focus-input100"></span>
        <span class="symbol-input100">
            <i class="fa fa-key" aria-hidden="true"></i>
        </span>
    </div>






    <div class="container-login100-form-btn">
        <button class="login100-form-btn">
            Continuer
        </button>
    </div>

    <div class="text-center p-t-12">


        <a class="txt2" href="/main/signup">
            Mot de passe oublié?
        </a>
        |
        <a class="txt2" href="/main/signup">
            S'inscrire
        </a>
    </div>

    {% else %}

    <div class="alert alert-info">Le lien utilisé a expiré , veuillez réenvoyer un lien en <a href="{% url 'main_app:password_reset' %}">cliquant ici</a></div>

    {% endif %}
</form>

{% endblock form %}

main_app/templates/authentification/reset_password_done.html
{% extends 'authentification/base_authentification.html' %}
{% load staticfiles %}
{% load widget_tweaks %}

{% block title} {{block.super}} - Récupérer mon mot de passe{% endblock title}

{% block form %}

<form class="login100-form validate-form" >


    <span class="login100-form-title"> 	</span>
    <div class="alert alert-success ">
       Un email de récupération de mot de passe vous a été envoyé.
    </div>


</form>

{% endblock form %}

main_app/templates/authentification/reset_password_form.html
{% extends 'authentification/base_authentification.html' %}
{% load staticfiles %}
{% load widget_tweaks %}

{% block title} {{block.super}} - Récupérer mon mot de passe{% endblock title}

{% block form %}

<form class="login100-form validate-form" method="POST" >
    {% csrf_token %}

    <span class="login100-form-title"> Récupérer mon mot de passe 	</span>

    {% include "messages.html" %}

    <div class="alert alert-warning">
        -Vous devez saisir un e-mail valide. <br>
        -Vous devez avoir activé votre compte lors de l'inscription.
    </div>


    {% for error in form_login.email.errors %}
        <span class="error-block">{{ error }}</span>
    {% endfor %}
    <div class="wrap-input100 validate-input" >
        {% render_field form_reset_password.email class="input100" placeholder="Email" %}
        <span class="focus-input100"></span>
        <span class="symbol-input100">
            <i class="fa fa-envelope" aria-hidden="true"></i>
        </span>
    </div>


    <div class="container-login100-form-btn">
        <button class="login100-form-btn">
            Continuer
        </button>
    </div>

    <div class="text-center p-t-12">


        <a class="txt2" href="/main/login">
            Se connecter
        </a>
        |
        <a class="txt2" href="/main/signup">
            S'inscrire
        </a>
    </div>
</form>

{% endblock form %}

main_app/templates/authentification/sign_up.html
{% extends 'authentification/base_authentification.html' %}
{% load staticfiles %}
{% load widget_tweaks %}

{% block title %} {{block.super}} S'inscrire{% endblock title %}

{% block form %}

<form class="login100-form validate-form" method="POST" action="/main/signup">
    {% csrf_token %}

    <span class="login100-form-title"> Inscription 	</span>

    {% include "messages.html" %}


    {% for error in form_inscription.username.errors %}
        <span class="error-block">{{ error }}</span>
    {% endfor %}
    <div class="wrap-input100 validate-input">
        {% render_field form_inscription.username class="input100" placeholder="Nom d utilisateur" %}
        <span class="focus-input100"></span>
        <span class="symbol-input100">
            <i class="fa fa-envelope" aria-hidden="true"></i>
        </span>

    </div>

    {% for error in form_inscription.password.errors %}
        <span class="error-block">{{ error }}</span>
    {% endfor %}
    <div class="wrap-input100 validate-input" >
        {% render_field form_inscription.password class="input100" placeholder="Mot de passe" %}
        <span class="focus-input100"></span>
        <span class="symbol-input100">
            <i class="fa fa-key" aria-hidden="true"></i>
        </span>

    </div>

    {% for error in form_inscription.confirmer_votre_mot_de_passe.errors %}
        <span class="error-block">{{ error }}</span>
    {% endfor %}
    <div class="wrap-input100 validate-input" >
        {% render_field form_inscription.confirmer_votre_mot_de_passe class="input100" placeholder="Confirmez votre mot de passe" %}
        <span class="focus-input100"></span>
        <span class="symbol-input100">
            <i class="fa fa-key" aria-hidden="true"></i>
        </span>

    </div>

    {% for error in form_inscription.email.errors %}
        <span class="error-block">{{ error }}</span>
    {% endfor %}
    <div class="wrap-input100 validate-input" >
        {% render_field form_inscription.email class="input100" placeholder="Email" %}
        <span class="focus-input100"></span>
        <span class="symbol-input100">
            <i class="fa fa-envelope" aria-hidden="true"></i>
        </span>

    </div>

    {% for error in form_inscription.first_name.errors %}
        <span class="error-block">{{ error }}</span>
    {% endfor %}
    <div class="wrap-input100 validate-input" >
        {% render_field form_inscription.first_name class="input100" placeholder="Prénom" %}
        <span class="focus-input100"></span>
        <span class="symbol-input100">
            <i class="fa fa-address-card-o" aria-hidden="true"></i>
        </span>

    </div>

    {% for error in form_inscription.last_name.errors %}
        <span class="error-block">{{ error }}</span>
    {% endfor %}
    <div class="wrap-input100 validate-input" >
        {% render_field form_inscription.last_name class="input100" placeholder="Nom" %}
        <span class="focus-input100"></span>
        <span class="symbol-input100">
            <i class="fa fa-address-card" aria-hidden="true"></i>
        </span>

    </div>




    <div class="container-login100-form-btn">
        <button class="login100-form-btn">
            S'inscrire
        </button>
    </div>

    <div class="text-center p-t-12">
						<span class="txt1">
							Déjà membre ?
						</span>
        <a class="txt2" href="/main/login">
            Se connecter
        </a>
    </div>
</form>

{% endblock form %}