ecommerce/urls.py
from django.urls import path
from ecommerce import views

app_name = 'e_commerce'
urlpatterns = [
    path('', views.index, name='index'),
    path('<int:id_request>/', views.test, name='test'),
    path('search/', views.search, name='search'),
    path('products/', views.products, name='products'),
    # ADD PRODUCT
    path('products/add/', views.add_product, name='add_product'),
    path('products/add/upload_image/', views.product_upload_image, name='product_upload_image'),
    path('products/add/delete_image/<int:image_id>/', views.product_delete_image, name='product_delete_image'),
    path('products/add/stock/', views.product_add_stock, name='product_add_stock'),
    path('products/add/specification/', views.product_add_specification, name='product_add_specification'),
    path('products/add/detail/', views.product_add_detail, name='product_add_detail'),
    path('products/add/tag/', views.product_add_tag, name='product_add_tag'),
    path('products/add/cancel/', views.product_cancel, name='product_cancel'),
    path('product/update/<int:product_id>/', views.update_product, name='product_update'),
    path('products/update/upload_image/<int:product_id>/', views.up_product_upload_image, name='up_product_upload_image'),
    path('products/update/delete_image/<int:product_id>/<int:image_id>/', views.up_product_delete_image, name='up_product_delete_image'),
    path('products/update/delete_spec/<int:product_id>/<int:spec_id>/', views.up_product_delete_spec, name='up_product_delete_spec'),
    path('products/update/delete_detail/<int:product_id>/<int:detail_id>/', views.up_product_delete_detail, name='up_product_delete_detail'),
    path('products/update/delete_stock/<int:product_id>/<int:stock_id>/', views.up_product_delete_stock, name='up_product_delete_stock'),
    path('products/update/stock/<int:product_id>/', views.up_product_add_stock, name='up_product_add_stock'),
    path('products/update/specification/<int:product_id>/', views.up_product_add_specification, name='up_product_add_specification'),
    path('products/update/detail/<int:product_id>/', views.up_product_add_detail, name='up_product_add_detail'),
    path('products/update/tag/<int:product_id>/', views.up_product_add_tag, name='up_product_add_tag'),
    path('account/upgrade/', views.create_store, name='create_store'),
    path('products/<str:type_search>/<str:id_search>/', views.products, name='products'),
    path('products_sub/<str:type_search>/<str:id_search>/', views.products_sub, name='products_sub'),
    path('product/', views.display_product, name='product'),
    path('product/<str:id_product>/', views.display_product, name='product'),
    path('quick_view/<str:id_product>/', views.quick_view, name='quick_view'),
    path('checkout/', views.checkout, name='checkout'),
    path('order/history/', views.order_history, name='order_history'),
    path('information/order/<str:id_order>/', views.order_information, name='order_information'),
    path('suppliers/', views.suppliers_list, name='suppliers'),
    path('supplier/<str:id_supplier>/', views.display_supplier, name='supplier'),
    path('account/products/', views.your_products, name='your_products'),
    path('product/remove/', views.remove_product, name='remove_product'),
    path('categories/', views.list_categories, name='list_categories'),
    path('review/', views.review, name='review'),
    path('orders/processing/', views.processing_orders, name="processing_orders"),
    path('orders/all/', views.all_orders, name="all_orders"),
    path('order/update/', views.update_order, name="update_order"),
    #--------------- Cart - wish list - compare - contact supplier
    path('cart/', views.cart, name='cart'),
    path('cart/update_cart/', views.update_cart, name='update_cart'),
    path('cart/update_color_cart', views.update_color_cart, name='update_color_cart'),
    path('cart/remove_from_page_cart', views.remove_from_page_cart, name='remove_from_page_cart'),
    path('wish_list/', views.wish_list, name='wish_list'),
    path('wish_list/add_from_wish/', views.add_from_wish, name='add_from_wish'),
    path('wish_list/remove_from_wish/', views.remove_from_wish, name='remove_from_wish'),
    path('compare/', views.compare, name='compare'),
    path('compare/add_from_compare/', views.add_from_compare, name='add_from_compare'),
    path('compare/remove_from_compare/', views.remove_from_compare, name='remove_from_compare'),
    path('add_to_compare', views.add_to_compare, name='add_to_compare'),
    path('add_to_wish_list', views.add_to_wish, name='add_to_wish_list'),
    path('add_to_cart', views.add_to_cart, name='add_to_cart'),
    path('remove_from_cart', views.remove_from_cart, name='remove_from_cart'),
    path('contact_supplier/<int:id_product>/', views.contact_supplier, name='contact_supplier'),
    # ------------ Easy
    path('contact-us/', views.contact_us, name='contact-us'),
    path('my-account/', views.my_account, name='my_account'),
    # ------------ Static pages
    path('FAQ/', views.faq, name='faq'),
    path('sitemap/', views.sitemap, name='sitemap'),
    path('about-us/', views.about_us, name='about-us'),
    #------------- Paypal
    path('paypal/process', views.paypal_process, name='paypal_process'),
    path('paypal/done', views.paypal_done, name='paypal_done'),
    path('paypal/cancel', views.paypal_cancel, name='paypal_cancel'),
]

espr/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include, url
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('e_commerce/', include(('ecommerce.urls'), namespace='e_commerce')),
    url(r'^paypal/', include('paypal.standard.ipn.urls')),
    path('main/', include('main_app.urls')),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

ecommerce/models.py
from django.db import models
from django.contrib.auth.models import User
import time
import os
import uuid
from django.utils.deconstruct import deconstructible
from django.utils import timezone
from main_app.models import Profil
from ckeditor.fields import RichTextField


# For rename the file before save
@deconstructible
class PathAndRename(object):
    def __init__(self, sub_path):
        self.path = sub_path

    def __call__(self, instance, filename):
        # eg: filename = 'my uploaded file.jpg'
        ext = filename.split('.')[-1]  # eg: 'jpg'
        uid = uuid.uuid4().hex[:10]  # eg: '567ae32f97'

        # eg: 'my-uploaded-file'
        new_name = '-'.join(filename.replace('.%s' % ext, '').split())

        # eg: 'my-uploaded-file_64c942aa64.jpg'
        renamed_filename = '%(new_name)s_%(uid)s.%(ext)s' % {'new_name': new_name, 'uid': uid, 'ext': ext}

        # eg: 'images/2017/01/29/my-uploaded-file_64c942aa64.jpg'
        return os.path.join(self.path, renamed_filename)


class Address(models.Model):
    company = models.CharField(max_length=254, blank=True)
    address = models.TextField()
    city = models.CharField(max_length=254)
    post_code = models.CharField(max_length=254)
    country = models.CharField(max_length=254)
    region = models.CharField(max_length=254)


class CommerceCategory(models.Model):
    name = models.CharField(max_length=200)
    image_path = time.strftime('images/%Y/%m/%d')
    image = models.ImageField(upload_to=PathAndRename(image_path))

    def __str__(self):
        return self.name


class CommerceSCategoryOne(models.Model):
    name = models.CharField(max_length=200)
    category = models.ForeignKey(CommerceCategory, on_delete=models.CASCADE)

    def __str__(self):
        return self.name


class CommerceSCategoryTwo(models.Model):
    name = models.CharField(max_length=200)
    category_one = models.ForeignKey(CommerceSCategoryOne, on_delete=models.CASCADE)

    def __str__(self):
        return self.name


class CommerceSCategory(models.Model):
    name = models.CharField(max_length=200)
    category_two = models.ForeignKey(CommerceSCategoryTwo, on_delete=models.CASCADE)

    def __str__(self):
        return self.name


class Brand(models.Model):
    name = models.CharField(max_length=200)
    image_path = time.strftime('images/%Y/%m/%d')
    image = models.ImageField(upload_to=PathAndRename(image_path), blank=True)

    def __str__(self):
        return self.name


class Tag(models.Model):
    name = models.CharField(max_length=20)

    def __str__(self):
        return self.name


class Shop(models.Model):
    name = models.CharField(max_length=200)
    image_path = time.strftime('images/%Y/%m/%d')
    image_profile = models.ImageField(upload_to=PathAndRename(image_path))
    image_cover = models.ImageField(upload_to=PathAndRename(image_path))
    description = models.TextField(null=True, blank=True)
    number_visitors = models.IntegerField(default=0)
    date_creation = models.DateField(auto_now_add=True)
    owner = models.OneToOneField(Profil, null=False, on_delete=models.CASCADE)
    address = models.CharField(max_length=300, null=True, blank=True)
    tel = models.CharField(max_length=30, null=True)
    approved = models.BooleanField(default=False)
    categories = models.ManyToManyField(CommerceSCategoryOne, blank=True)

    def __str__(self):
        return self.name


class Product(models.Model):
    name = models.CharField(max_length=200)
    price = models.DecimalField(max_digits=15, decimal_places=2, default=0)
    image_path = time.strftime('images/%Y/%m/%d')
    image = models.ImageField(upload_to=PathAndRename(image_path))
    date_add = models.DateField(auto_now_add=True)
    cat = models.ForeignKey(CommerceSCategory, on_delete=models.CASCADE, null=True)
    brand = models.ForeignKey(Brand, on_delete=models.CASCADE, blank=True, null=True)
    accessories = models.ManyToManyField("self", blank=True)
    tags = models.ManyToManyField(Tag, blank=True)
    number_views = models.IntegerField(default=0, null=False, blank=False, editable=True)
    quantity_min = models.IntegerField(default=1, null=True, blank=True)
    unit = models.CharField(max_length=200, default='Piece')
    is_pro = models.BooleanField(default=False)
    supplier = models.ForeignKey(Shop, on_delete=models.CASCADE, null=True)
    packaging_detail = models.CharField(max_length=1000, null=True, blank=True)
    delivery_time = models.CharField(max_length=1000, null=True, blank=True)
    content = RichTextField(default=' ')
    price_from = models.BooleanField(default=False)
    old_price = models.DecimalField(max_digits=15, decimal_places=2, null=True, blank=True)
    active = models.BooleanField(default=False)
    approved = models.BooleanField(default=False)

    def __str__(self):
        return self.name


class CommerceInformation(models.Model):
    name = models.CharField(max_length=250, default="detail")
    value = models.TextField()
    product = models.ForeignKey(Product, on_delete=models.CASCADE)

    def __str__(self):
        return 'info {0} {1}'.format(str(self.pk), self.product.name)


class CommerceImage(models.Model):
    image_path = time.strftime('images/%Y/%m/%d')
    image = models.ImageField(upload_to=PathAndRename(image_path))
    product = models.ForeignKey(Product, on_delete=models.CASCADE, null=True)

    def __str__(self):
        return 'image {0} {1}'.format(str(self.pk), self.product.name)


class CommerceRatting(models.Model):
    value = models.DecimalField(max_digits=5, decimal_places=2)
    comment = models.TextField(blank=True)
    name = models.CharField(max_length=200)
    email = models.EmailField(max_length=254),
    date_add = models.DateField(auto_now_add=True, editable=True)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)

    def __str__(self):
        return "vote {0},  {1} : {2}".format(str(self.pk), str(self.value), self.product.name)


class Color(models.Model):
    name = models.CharField(max_length=200)
    code_hex = models.CharField(max_length=200)

    def __str__(self):
        return self.name


class Stock(models.Model):
    quantity = models.IntegerField(default=0)
    first_quantity = models.IntegerField(default=0)
    price_sup = models.DecimalField(max_digits=15, decimal_places=2, default=0)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    color = models.ForeignKey(Color, on_delete=models.CASCADE, default=1)

    def __str__(self):
        return '{0} de {1} {2}'.format(str(self.quantity), self.product.name, self.color.name)
    
    def new_price(self):
        return self.product.price + self.price_sup
    
    def percent(self):
        return (self.quantity * 100) / self.first_quantity
    
    def sold(self):
        return self.first_quantity - self.quantity


class Specification(models.Model):
    name = models.CharField(max_length=200)
    value = models.CharField(max_length=1000)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)

    def __str__(self):
        return self.name + ' ' + self.product.name


class Sale(models.Model):
    percentage = models.IntegerField()
    date_end = models.DateTimeField(blank=False, default=timezone.now)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    is_daily = models.BooleanField(default=False)

    def __str__(self):
        return str(self.percentage) + "% for " + self.product.name
    
    def new_price(self):
        return self.product.price - ((self.product.price*self.percentage)/100) 


class WishList(models.Model):
    user = models.ForeignKey(Profil, on_delete=models.CASCADE)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)

    def __str__(self):
        return self.user.user.username + ' ' + self.product.name


class Cart(models.Model):
    quantity = models.IntegerField(default=1)
    user = models.ForeignKey(Profil, on_delete=models.CASCADE)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    color = models.ForeignKey(Color, on_delete=models.CASCADE)

    def total(self):
        return self.product.price * self.quantity

    def __str__(self):
        return '{0} {1} de {2}'.format(str(self.quantity), self.product.name, self.user.user.username)


payment_method = (('Cash On Delivery', 'Cash On Delivery'), ('Paypal', 'Paypal'))
delivery_method = (('Free Shipping', 'Free Shipping'), ('Flat Shipping Rate', 'Flat Shipping Rate'))


class Order(models.Model):
    amount = models.DecimalField(max_digits=15, decimal_places=2)
    date = models.DateField(auto_now_add=True)
    status = models.CharField(max_length=200, default="Created")
    payment_method = models.CharField(max_length=20, choices=payment_method, default='Cash On Delivery')
    delivery_method = models.CharField(max_length=20, choices=delivery_method, default='Free Shipping')
    comment = models.TextField(null=False, blank=True, default="")
    track_number = models.CharField(max_length=300, null=True, blank=True)
    date_payment = models.DateField(null=True, blank=True)
    date_complete = models.DateField(null=True, blank=True)
    user = models.ForeignKey(Profil, on_delete=models.SET_NULL, null=True)

    def __str__(self):
        return 'Order {0} de {1}'.format(str(self.pk), self.user.user.username)


class OrderLine(models.Model):
    quantity = models.IntegerField()
    total = models.DecimalField(max_digits=15, decimal_places=2)
    order = models.ForeignKey(Order, on_delete=models.SET_NULL, null=True)
    product = models.ForeignKey(Product, on_delete=models.SET_NULL, null=True)
    color = models.ForeignKey(Color, on_delete=models.SET_NULL, null=True)

    def price_unit(self):
        return self.total / self.quantity


class Slide(models.Model):
    image_path = time.strftime('slides/%Y/%m/%d')
    image = models.ImageField(upload_to=PathAndRename(image_path))
    product = models.ForeignKey(Product, on_delete=models.CASCADE)

ecommerce/templates/ecommerce/cart.html
{% extends 'ecommerce/base.html' %}
{% load static %}
{% load humanize %}
{% block content %}
<div class="main-container container">
    <ul class="breadcrumb">
        <li><a href="{% url 'e_commerce:index' %}">Acceuil</a></li>
        <li><a href="{% url 'e_commerce:my_account' %}">Mon compte</a></li>
        <li><a href="#"><b>Chariot</b></a></li>
    </ul>
    <div class="row">
        <!--Middle Part Start-->
        {% if message_error %}
        <div class="alert alert-danger" role="alert" style="margin: 14px 14px 0;">
            <strong>Oups !</strong> {{ message_error }}
        </div>
        {% endif %}
        {% if message_success and not message_error %}
            <div id="success" class="alert alert-success" role="alert" style="margin: 14px 14px 0;">
              <strong>Succès !</strong> {{ message_success }}
            </div>
        {% endif %}
        <div id="content" class="col-sm-12">
            {# ---------------------------- Cart ---------------------------------- #}
            <h2 class="title">Chariot</h2>
            <div class="table-responsive form-group" style="margin-bottom: 0;margin-top: 25px;">
                <table class="table table-bordered">
                    <thead>
                        <tr>
                            <td class="text-center col-md-1">Image</td>
                            <td class="text-center col-md-3">Nom de Produit</td>
                            <td class="text-center col-md-1">Marque</td>
                            <td class="text-center col-md-1">Couleur</td>
                            <td class="text-center col-md-2">Quantité</td>
                            <td class="text-center">Prix unitaire</td>
                            <td class="text-center">Total</td>
                        </tr>
                    </thead>
                    <tbody>
                    {% for el in cart %}
                        <tr>
                            <td class="text-center">
                                <a href="{% url 'e_commerce:product' el.product.pk %}">
                                    <img width="50px" height="50px" style="border: 0" src="{{ el.product.image.url }}" alt="Image {{ el.product.name }}" title="{{ el.product.name }}" class="img-thumbnail" />
                                </a>
                            </td>
                            <td class="text-center" style="padding-top: 12px;">
                                <a href="{% url 'e_commerce:product' el.product.pk %}">{{ el.product.name }}</a><br />
                            </td>
                            <td class="text-center" style="padding-top: 12px;">
                                {{ el.product.brand.name }}
                            </td>
                            <td class="text-center" style="padding-top: 12px;">
                                {% if el.product.stock_set.exists %}
                                    {% if el.product.stock_set.count == 1 and el.product.stock_set.first.color.name == "None" %}
                                        <input type="hidden" name="option[231]" value="0">
                                        Original
                                    {% else %}
                                        <form method="post" action="{% url 'e_commerce:update_color_cart' %}">
                                        {% csrf_token %}
                                            <input type="hidden" name="next"     value="{{ request.path }}" style="display: inline-block;">
                                            <input type="hidden" name="cart"     value="{{ el.pk }}" style="display: inline-block;">
                                            <div class="image_option_type form-group required"  style="display: inline-block">
                                                <ul class="product-options clearfix" id="input-option231">
                                                    {% for stock in el.product.stock_set.all %}
                                                        {% if stock.color.name == "None"%}
                                                        <li class="radio">
                                                            <label>{{ el.produt.stock_set.0.color.name  }}
                                                                <input class="image_radio" type="radio" name="option[231]" value="{{ stock.color.pk }}"> <img width="30px" height="30px" src="{% static 'ecommerce/image/none.png' %}" data-original-title="Original" class="icon icon-color">
                                                                <i class="fa fa-check"></i>
                                                                <label></label>
                                                            </label>
                                                        </li>
                                                        {% else %}
                                                            {% if el.color.name == stock.color.name %}
                                                                <li class="radio active">
                                                                    <label>
                                                                        <input class="image_radio" type="radio" name="option[231]" value="{{ stock.color.pk }}"> <img width="30px" height="30px" style="background-color: {{ stock.color.code_hex }}" data-original-title="{{ stock.color.name }} +{{ stock.price_sup|intcomma }} Dh" class="icon icon-color">
                                                                        <i style="margin-left: 3.5px" class="fa fa-check"></i>
                                                                        <label></label>
                                                                    </label>
                                                                </li>
                                                            {% else %}
                                                                <li class="radio">
                                                                    <label class="text-center">
                                                                        <input class="image_radio" type="radio" name="option[231]" value="{{ stock.color.pk }}"> <img width="30px" height="30px" style="background-color: {{ stock.color.code_hex }}" data-original-title="{{ stock.color.name }} +{{ stock.price_sup|intcomma }} Dh" class="icon icon-color">
                                                                        <i style="margin-left: 3.5px" class="fa fa-check"></i>
                                                                        <label></label>
                                                                    </label>
                                                                </li>
                                                            {% endif %}
                                                        {% endif %}
                                                    {% endfor %}
                                                    <li class="selected-option">
                                                    </li>
                                                </ul>
                                            </div>
                                            <button style="display: inline-block" type="submit" data-toggle="tooltip" title="Modifier" class="btn btn-primary">
                                                <i class="fa fa-clone"></i>
                                            </button>
                                        </form>
                                    {% endif %}
                                {% endif %}
                            </td>
                            <td class="text-left" style="padding-top: 12px;">
                                <div class="input-group btn-block quantity">
                                    <form style="display: inline-block; width: 80%" action="{% url 'e_commerce:update_cart' %}" method="post">
                                        {% csrf_token %}
                                        <input type="hidden" name="next"     value="{{ request.path }}" style="display: inline-block;">
                                        <input type="hidden" name="cart"     value="{{ el.pk }}" style="display: inline-block;">
                                        <input type="number" name="quantity" value="{{ el.quantity }}" style="width:74%; display: inline-block;" size="1" class="form-control" />
                                        <span class="input-group-btn" style="display: inline-block;min-width: 39px;" >
                                            <button type="submit" data-toggle="tooltip" title="Modifier" class="btn btn-primary">
                                                <i class="fa fa-clone"></i>
                                            </button>
                                        </span>
                                    </form>
                                    <form style="display: inline-block; width: 20%" action="{% url 'e_commerce:remove_from_page_cart' %}" method="post">
                                        {% csrf_token %}
                                        <input type="hidden" name="next"     value="{{ request.path }}" style="display: inline-block;">
                                        <input type="hidden" name="cart"     value="{{ el.pk }}" style="display: inline-block;">
                                        <span class="input-group-btn" style="display: inline-block;min-width: 40px;">
                                            <button type="submit" data-toggle="tooltip" title="Retirer" class="btn btn-danger">
                                                <i class="fa fa-times-circle"></i>
                                            </button>
                                        </span>
                                    </form>
                                </div>
                            </td>
                            <td class="text-center" style="padding-top: 12px;">{{ el.product.price|intcomma }} Dh</td>
                            <td class="text-center" style="padding-top: 12px;">{{ el.total|intcomma }} Dh</td>
                        </tr>
                    {% endfor %}
                    </tbody>
                </table>
            </div>
            {# -------------------------------------------------------------------- #}
            <div class="row">
                <div class="col-md-12">
                    <div class="buttons pull-right" style="text-transform: uppercase;">
                        <a href="{% url 'e_commerce:index' %}" style="background-color: #ea4c0f; color:white;" class="btn"><strong>Continuer l'Achat</strong></a>
                        <a href="{% url 'e_commerce:checkout' %}" style="background-color: #ea4c0f; color:white;" class="btn"><strong>Check-out</strong></a>
                    </div>
                    <div class="pull-right"
                         style="padding: 5px 40px; margin-right: 30px; border: 1px solid #ec971f; background: #ec971f; color: #FFF;">
                        <strong>Total : &nbsp;</strong>{{ total_price_in_cart|intcomma }} Dh</div>
                </div>
            </div>
        </div>
        <!--Middle Part End -->
    </div>
</div>
{% endblock %}

ecommerce/templates/ecommerce/sitemap.html
{% extends 'ecommerce/base.html' %}
{% load static %}
{% block content %}
<div class="main-container container">
    <ul class="breadcrumb">
        <li><a href="{% url 'e_commerce:index' %}">Accueil</a></li>
        <li><a href="#"><b>Carte du Site</b></a></li>

    </ul>
    <div class="row">
        <div id="content" class="col-sm-12">
            <h2 class="title">Carte du Site</h2>
            <div class="row">
                <div class="col-md-4 col-sm-6">
                    <ul class="simple-list arrow-list bold-list">
                        {% for category in categories %}
                        <li>
                            <a href="{% url 'e_commerce:products' 'category' category.pk %}">{{ category.name }}</a>
                        </li>
                        {% endfor %}
                    </ul>
                </div>
                <div class="col-md-4 col-sm-6">
                    <ul class="simple-list arrow-list bold-list">
                        <li><a href="{% url 'e_commerce:my_account' %}">My Account</a>
                            <ul>
                                <li><a href="{% url 'e_commerce:order_history' %}">Historique des Commandes</a></li>
                                <li><a href="{% url 'e_commerce:order_history' %}">Informations des Commandes</a></li>
                                <li><a href="{% url 'e_commerce:cart' %}">Chariot</a></li>
                                <li><a href="{% url 'e_commerce:wish_list' %}">Liste des Souhaits</a></li>
                                <li><a href="{% url 'e_commerce:compare' %}">Comparer les Produits</a></li>
                                <li><a href="{% url 'e_commerce:checkout' %}">Check-out</a></li>
                            </ul>
                        </li>
                        <li><a href="#sosearchpro">Search</a>
                        </li>
                        <li><a>Information</a>
                            <ul class="sitemap">
                                <li><a href="{% url 'e_commerce:about-us' %}">About Us</a>
                                </li>
                                <li><a href="{% url 'e_commerce:faq' %}">Faq</a>
                                </li>
                                <li><a href="{% url 'e_commerce:about-us' %}">404</a>
                                </li>
                                <li><a href="{% url 'e_commerce:contact-us' %}">Contact Us</a>
                                </li>
                            </ul>
                        </li>
                        <li><a href="#popular_tags">Tags Populaires</a></li>
                    </ul>
                </div>
                <div class="col-md-4 col-sm-6">
                    <ul class="simple-list arrow-list bold-list">
                        <li><a>Marque</a>
                            <ul class="sitemap">
                                {% for brand in brands %}
                                <li><a href="{% url 'e_commerce:products' 'brand' brand.pk %}">{{ brand.name }}</a>
                                </li>
                                {% endfor %}
                            </ul>
                        </li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}